### ISSUE TITLE
Possible race condition in `ArcIntern::drop`.

### ISSUE THREAD

**Issue by ryzhyk** [droundy/internment#11]
I believe this function has a potential race condition:

https://github.com/droundy/internment/blob/1d9703ff5184f4f3dbac1368d52976a5630d9966/src/lib.rs#L316

If a concurrent thread creates a new `ArcIntern` with the same value as the one being destroyed after we drop the ref count but before we take the mutex, then removing an entry from the map creates a dangling pointer.

**Comment by droundy** [comment]
I agree that it looks racy.  I'd welcome a pull request, probably just double checking the value of the count after taking the mutex to free.

If not, I'll get to this eventually myself.  Right now I'm pretty crazy busy, though.

**Comment by ryzhyk** [comment]
The only solution I can think of that is not racy is to take the mutex unconditionally on each `drop`. Checking->taking the mutex->checking again is still racy and can create leaks. If this sounds good to you, I will create a PR.

To add more context, I spent several days debugging a really nasty crash in my program that involved Java, a bunch of auto-generated Rust code and `internment` at the very bottom. In the end, I think the crash was caused by this race, so the problem is real. Since I was also worried about unsafe parts of this library that hinge on nuanced reasoning about memory ordering, I forked your code and implemented my own version of `ArcInterner` that relies on standard `Arc` and `Mutex` types and does not contain any unsafe code: https://crates.io/crates/arc-interner. (I am not saying that your unsafe code is buggy, in fact your reasoning seems perfectly sound, but it's also quite subtle, and, given how hard these things are to debug, I decided I did not want to take any chances).

**Comment by droundy** [comment]
I don't like the idea of making drop always take a global mutex, since it's like drop (and clone) to normally be as cheap as possible.

I think I see how checking then taking the mutex and rechecking could lead to a leak. If a new reference is added between the first check and taking the mutex, and then the new reference is also freed, then we could have a double free bug.

What about checking the count on creating a new ArcIntern? That would have the advantage of using the same atomic in every case to determine whether the value will persist. The hard part is figuring out what to do when a race is detected. Probably just drop the mutex, wait and try again would be simplest. Alternatively, we could allocate a new object and then rely on drop checking that the memory being dropped is the same as the current version before altering the hashmap.

By the way, I'm so sorry that my unsafe code caused you so much trouble!

**Comment by droundy** [comment]
I've just pushed a commit that fixes the data race by intentionally leaking the memory in the case where `drop` is called on an `ArcIntern` but fails to take the `Mutex` before a `new` is called that resurrects that item.  I don't feel *too* bad about the leak, which certainly beats a crash, and only happens on an item that is required at least twice.  But I'd love to come up with a better and non-leaky solution.  It just will take more than 20 minutes of thinking and coding.

I'd also *love* to have some sort of stress-tester for this code, but that would be a major effort.

**Comment by droundy** [comment]
I've just pushed a new commit that I think fixes this race condition without the leak.  The basic idea is to change the HashSet to hold a new reference-counted pointer type, so we can decouple freeing the memory from removing the data from the set.  Thus it won't hurt to remove it twice.

In terms of "what protects what", the Mutex is now protecting the HashSet, while the reference counting is "protecting" the data memory allocation.  We remove the element from the HashSet when the count reaches 1, not 0.

I'm not closing this just yet, because I'd like a code review if you can find the time.  I've added some benchmarks, including against the arc-interner crate,  It looks like this new implementation is faster at `clone`/`drop` (as it should be) but slower at `new`.  Since I use `Intern` mostly myself, I'd like your opinion on optimization priorities.  I'd be happy to accept the `arc-interner` implementation if you'd prefer that approach.  But even better would be to make my implementation of `new` faster, if we could figure out how to do that.  Since interning is about speed, optimization matters (as well as correctness).

**Comment by ahornby** [comment]
With current master a1f04a69c7fba7919f9cba13ea600c39e11654e3 I see use after free is at src/lib.rs:444:3 inside ArcIntern::drop"

   let count_is = unsafe { (*self.pointer).count.load(Ordering::Relaxed) };

Which was allocated at src/lib.rs:351:29 from ArcIntern::new()

  let ptr = Box::leak(Box::new(RefCount { count: AtomicUsize::new(2), data: val }));

and freed by src/lib.rs:492:9 in Arc::drop called from src/lib.rs:459:9 in ArcIntern::drop

Running from a build at the earlier "leaky" fix 3bf1b697bdd64598777df39723fdbc93c632acdf, I see similar problem, line numbers a bit different.

Sorry no solution, but the race appears to still be there.

**Comment by droundy** [comment]
Before I get to my computer to see if I can reason this out I wanted to thank you for checking this out for me!

**Comment by droundy** [comment]
Okay, I think I see the bug (and a possible fix), but am wondering how you found the bug so quickly? It would be great to get some fuzzing or similar into the test process, since clearly I'm unable to reliably reason about concurrent code.

**Comment by droundy** [comment]
BTW, the error on my part was that I considered the possibility of adding a reference after our drop checked the count, but didn't consider afternoon e and then removing the reference and also freeing the memory.  It's now obvious, but that's hindsight for you.

**Comment by droundy** [comment]
The solution is that once we have decremented the count *any* access to the data must come through the HashMap, since we've given up our right to the data. The only exception is if there was no other reference to the data, in which case we can free it, since no one else could have done so behind our back.

**Comment by ahornby** [comment]
I've been running a heavily a multithreaded workload which showed the problem when built with internment instead of arc-intern and with ASAN enabled.   The workload code is open source, but currently not really runnable externally: https://github.com/facebookexperimental/eden/tree/master/eden/mononoke/walker/src.   

I didn't do the internal ASAN setup,  so can't comment on what was involved there (some quick googling found https://github.com/google/mundane/commit/0148297bf1c5bb8ccc8acbc7abcc15cb4b53d6ee as a possible example?)

I'll may have some time to look at internment tomorrow UK time,  if you have a candidate fix I'll try it out, if not I might have a go at one.

**Comment by droundy** [comment]
Right now I'm thinking that if better implement a good test that reproduces the issue before fixing it. Once I fix it, the level of satisfaction in writing the test goes way down. I have a pretty clear idea how to fix the bug, which shouldn't be hard, but better to get that test written first, and ideally running on CI.

**Comment by ahornby** [comment]
I managed to reproduce the use after free from cargo test, PR with change is https://github.com/droundy/internment/pull/14

I've also potentially got a fix in https://github.com/ahornby/internment/commit/ba72b96a8e64a527beeccef73fd3240e4d623a00  Still testing that one (no panics or ASAN warnings so far)

**Comment by droundy** [comment]
Okay, now I really believe that the bug is fixed. My new approach is actually quite simple. Once the reference count reaches zero The thread that drops the reference count to zero owns the object. If another thread tries to create an interned copy of the same object it will notice that the reference count is zero and instead wait for the object to be freed. The key is the waiting which has the result that only one thread which is well known is able to do the actual freeing and there is not a competition between two threads that might both be trying to free the same object. On top of that, the object is only freed when the mutex is held which means that any thread that accesses the object via the mutex will not be able to access it after it is freed.

**Comment by droundy** [comment]
Looks like there is still a race condition... Need to debug this yet again.

**Comment by droundy** [comment]
Never mind!

**Comment by mbrubeck** [comment]
For the record, the fix described in https://github.com/droundy/internment/issues/11#issuecomment-656811412 is in commit https://github.com/droundy/internment/commit/632207b0e639649f76f547f17ccd97a6c409161e and was published in internment 0.4.0.
