### ISSUE TITLE
Feature flags on individual Intern types?

### ISSUE THREAD

**Issue by dvtomas** [droundy/internment#18]
I'm only using `Intern`. For the sake of compilation speed, would it make sense to put all the three Intern types (`Intern`, `ArcIntern`, `LocalIntern`) behind feature flags, so I could opt out of those I don't use? If I'm only using `Intern`, would that mean some dependencies would go away as well?

**Comment by droundy** [comment]
That's something that's testable. I'm not sure when I'll have time to look at this, but would be delighted if you found time to create a pull request.

Off the top of my head, with the next release dashmap will be required for ArcIntern only.

The tinyset dependency could go behind a feature flag with some refactoring. I think it's used for the Debug implementation.

 I'd prefer to see some compile timings data, or binary size data before accepting a pull request.

**Comment by droundy** [comment]
I'll close this, since we now have feature flags for ArcIntern and for tinyset support, which eliminates all the dependencies except for `hashbrown` (used by both Intern and LocalIntern) and `once_cell` (used by everything).  Hopefully eventually the needed raw_entry interface will move into `std::collections::HashMap` and we can remove the `hashbrown` dependency.

**Comment by dvtomas** [comment]
Perfect, thank you.
