### ISSUE TITLE
Loosen `T` for `ArcIntern` to `?Sized`

### ISSUE THREAD

**Issue by gwy15** [droundy/internment#39]
Hi, I'm looking for a replacement for `Arc<str>`. From my understanding, `ArcIntern` currenly does not allow `T` to be `?Sized`. <del>I tried to implement it, but from my understanding, it requires `alloc::Allocator` related features which is an unstable feature.</del>

<del>It would be awesome if the library could provide a feature named `dst` and when compiled with `nightly` toolchain, allow types like `ArcIntern<str>`.</del>

I implemented this feature in #40 in stable Rust with some unsafe code.

**Comment by droundy** [comment]
I might be able to look at this on the weekend. I agree that this would be great, and it should be possible, but I remember working a bit on `?Unsized` before and as you've noticed it's a bit of a pain.

**Comment by droundy** [comment]
I had the idea that perhaps a good approach would be to use [weak_table](https://docs.rs/weak-table/latest/weak_table/) instead of dashmap. We'd have to go back to using a mutex to prospect the map, which might be a bummer in terms of performance, but getting rid of the scary unsafe code plus enabling ArvIntern<str> might be worth it (depending on the cost).

**Comment by droundy** [comment]
I believe this has been done for a while now.
